version: '3.8'
services:
  jupyter:
    container_name: template_glue
    command: /home/glue_user/jupyter/jupyter_start.sh
    environment:
      - DISABLE_SSL=true
    image: amazon/aws-glue-libs:glue_libs_3.0.0_image_01
    ports:
      - '4040:4040'
      - '18080:18080'
      - '8998:8998'
      - '8888:8888'
    volumes:
      - /Users/ignaciodiaz/.aws:/home/glue_user/.aws
      - ${PWD}:/home/glue_user/workspace/jupyter_workspace/template/